version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/php-fpm/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app:cached
      - app-vendor-volume:/app/vendor
    working_dir: /app
  web:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - ${WEB_HTTP_PORT:-80}:80
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: ./docker/local/mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/local/mysql/logs:/var/log/mysql:delegated
  mailhog:
    build:
      context: .
      dockerfile: ./docker/local/mailhog/Dockerfile
    ports:
      - ${MAILHOG_SMTP_PORT:-1025}:1025
      - ${MAILHOG_HTTP_PORT:-8025}:8025
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "${LOCALSTACK_HTTP_PORT:-8026}:8080"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=sns,dynamodb
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_TMPDIR:-/tmp/localstack}:/tmp/localstack"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - ${DYNAMODB_ADMIN_PORT:-8001}:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
    depends_on:
      - localstack
  redis:
    build:
      context: .
      dockerfile: ./docker/local/redis/Dockerfile
  api-doc:
    image: swaggerapi/swagger-ui
    ports:
      - ${API_DOC_PORT:-8080}:8080
    volumes:
      - ./document/openapi/generated/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
  api-editor:
    image: swaggerapi/swagger-editor
    ports:
      - ${API_EDIT_PORT:-8081}:8080
  db-doc:
    build:
      context: .
      dockerfile: ./docker/local/tbls/Dockerfile
    volumes:
      - ./document:/work
    command: doc --force mysql://root:${DB_ROOT_PASSWORD:-root}@db:3306/${DB_DATABASE:-laravel}

volumes:
  app-vendor-volume:
  db-volume:
