openapi: 3.0.2

info:
  title: studio-app APIs
  version: "0.1"
servers:
  - url: "http://localhost"
    description: ローカルサーバ

paths:
  /health-check:
    $ref: ./paths/admin/health-check.yml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: supporter
    description: "サポーター用API"
